from polinome import *

"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2= 1/2*n^2 + 1/2*n	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2 = 3/2*n^2 - 1/2*n	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1) = 2*n^2 - n	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

def main():
    triangle = Polinome(0, 1/2, 1/2)
    pentagonal = Polinome(0, -1 / 2, 3 / 2)
    hexagonal = Polinome(0, -1, 2)

    the_intersection = triangle.intersection(pentagonal.intersection(hexagonal.get_results()))
    n = max(the_intersection)

    print(f"T{triangle.get_index(n)} = P{pentagonal.get_index(n)} = H{hexagonal.get_index(n)} = {n}")


if __name__ == '__main__':
    main()

"""
this is the result T55385 = P31977 = H27693 = 1533776805
"""